Doc/cmus.txt, command_mode.c
This small patch adds a `:pwd` command to cmus that allows the user to query the current working directory (which can be set with `:cd`)
=> Added pwd command

search.c
The wrap_search setting is ignored when the search_next function skips the current match. This prevents search from wrapping if the current match is the last (or first, when searching in reverse) item in view. For instance, searching for "search" in settings will not wrap, since "wrap_search" matches and is the last item in that view.
This is fixed by skipping the current match using the same code as in the search loop, which correctly handles the wrap_search setting.
=> Fix search wrapping

ui_curses.c
```
ui_curses.c: In function 'ui_curses_notify':
ui_curses.c:2094:2: warning: ignoring return value of 'write',
declared with attribute warn_unused_result [-Wunused-result]
write(notify_in, &c, 1);
^
ui_curses.c: In function 'notify_init':
ui_curses.c:2332:2: warning: ignoring return value of 'pipe',
declared with attribute warn_unused_result [-Wunused-result]
pipe(fildes);
^
ui_curses.c: In function 'main_loop':
ui_curses.c:2210:4: warning: ignoring return value of 'read',
declared with attribute warn_unused_result [-Wunused-result]
read(notify_out, buf, sizeof(buf));
^
```
=> Fix -Wunused-result warnings

alsa.c
If you have `pulseaudio` and `pulseaudio-alsa` installed and when you start a new song, cmus will show that the song is already at the 24 seconds mark even though the song plays normally. When you seek, cmus will skip forward 24 seconds (+- what you're seeking.) 
If you start pulseaudio with verbose output, you can see the following message: 
```
D: [pulseaudio] alsa-util.c: Maximum hw buffer size is ___23777 ms___
D: [pulseaudio] alsa-util.c: Set buffer size first (to 88200 samples), period size second (to 88200 samples).
```
So it seems that when we're using the pulseaudio alsa sink, cmus will send alsa 24 seconds of audio before alsa tells it that the buffer is full. When you seek, cmus tells alsa to discard the buffer, which explains why we skip forward 24 seconds.
This patch tells …
=> fix pulseaudio alsa-sink 24s bug

Doc/cmus.txt, contrib/_cmus, main.c, misc.c, ui_curses.c
This has basically the same effect as #68 .
Sometimes I am using several cmus instances at the same time and this is no longer possible since XDG_RUNTIME_DIR/cmus-socket is being used, so now the socket is located in CMUS_SOCKET if this env is set.
=>  Add CMUS_SOCKET environment variable.

data/jellybeans.theme
Adds a color scheme based on [Jellybeans.vim](https://github.com/nanotech/jellybeans.vim)
=> Jellybeans colorscheme

ffmpeg.c
I am not sure if we should check if FFmpeg's version supports TAK (as some relatively old versions do not). Let me know if that's the case.
=> Add support for *.tak files as per cmus/cmus#319

ffmpeg.c
FFmpeg >= 2.8 (libavformat >=56.40.101) is required
for playing *.aa files.
A sample *.aa file can be downloaded from,
http://samples.ffmpeg.org/audible/
=> Add support for *.aa files

http.c, input.c
http_parse_uri doesn't work correctly when the URI's path contains an "at" or a colon. For example, the valid URI http://somedomain.com/path:withcolon fails to parse. Also, the proxy-value is undefined when http_parse_uri fails (e.g.: adding the stream http://somedomain.com:/ segfaults on my machine when free is called).
=> Fix HTTP-URI parsing bugs

ui_curses.c
Previously, if you resize your terminal to less than 8 lines, there was weird behavior when moving around or when the track changed such as the current track line disappearing or partially disappearing and then reappearing. This changes the min height to be 2 lines so that as long as there is space to show the current track line it does but if there is only one line display current selection.
=> Fix for short terminal

data/gruvbox.theme
Added a gruvbox theme for myself that might be worth including in the cmus master since it's a popular vim theme. Screenshot shows my cmus next to vim. I tried to make style choices so that it would look similar to vim.
=> adds gruvbox theme

configure
The ffmpeg plugin uses functions from libavcodec, so ensure that it is linked
against libavcodec.
=> Link against libavcodec

configure
This is a small commit to to check for the presence of AudioUnit framework when configuring the build. This PR is in relation to #374.
=> Added check for AudioUnit when configuring

Doc/cmus-remote.txt, Doc/cmus.txt, command_mode.c, main.c, player.c, player.h
which only pauses if playing, but does not resume when stopped/paused
implements #403 
I'll add a dedicated cmus-remote command and the relevant documentation once you think the implementation is ok and worth integrating.
=> adding a player-pause-no-resume command

AUTHORS, command_mode.c
Seeking when the player is paused moves the position without
unpausing. This makes seeking when the player is stopped work in a
similar way.
Fixes #438
=> Make the seek command not start playing when the player was stopped.

Doc/cmus.txt
- Fix some highlighting that got out of control
- Trailing whitespace
=> Trivial fixes to man pages

coreaudio.c
Only perform sample rate synchronization when user opt in sync_sample_rate. Other values in the format should be transparent for CoreAudio conversion. Particularly, If user have high end DACs (such as 24 bit DAC) it's always better to select higher bit depth rather than sync it with the audio file. This gives user more freedom adjusting software volume without losing precision.
=> remove device stream sync code

Doc/cmus.txt, Makefile, command_mode.c, configure, locking.c, locking.h, mpris.c, mpris.h, options.c, options.h, player.c, player.h, track_info.c, track_info.h, ui_curses.c, utils.h
At long last this PR continues the work started in #90. Thanks to the new sd-bus API it's now much easier to implement MPRIS support in plain C. This allows cmus to integrate with various desktop environments. See the screenshot below. Some minor changes had to be made to the existing code but nothing major. The `track_info` structure now has a `uid` field which is a unique integer and allows each track to be identified by MPRIS clients. Not every feature is implemented. For example, the CanGoNext property always returns true even if there is no next track to play. Implementing this properly would require more refactoring. This can be done in the future.
=> mpris support

ui_curses.c
ncurses already sleeps in the first getch call if it returns an ESC.
Sleeping in the second call is unnecessary because the character (if
any) is already available.
The user can set how long ncurses sleeps by setting the ESCDELAY
environment variable to the time in milliseconds. For example
$ ESCDELAY=25 cmus
will make pressing ESC in command mode leave it almost instantaneously.
Also remove an unnecessary cbreak call because cbreak and halfdelay are
mutually exclusive.
=> Make second getch after ESC non-blocking

configure, sndio.c
I was trying to play a 24-bit encoded FLAC file in cmus using the sndio output plugin, which failed with an error message saying that it's unsupported.  With just a little bit of extra code it works.
I also removed `sys/audioio.h` which is not needed to compile cmus on OpenBSD 5.9 and does not exist on FreeBSD.
While here I also enabled checking for sndio on FreeBSD in the configure script.
=> Support 24-bit/32-bit encodings in sndio output plugin

coreaudio.c
fix a bug for CoreAudio's 24 bit playback. when buffer is not cleared correctly, it is possible the data position is wrongly assigned.
=> flush ring buffer when coreaudio_drop

command_mode.c, filters.c, filters.h
I looked through the issues listed in #554 and this should resolve them.
Just some minor fixes to differentiate between the two commands within _filters_activate_. Would be nicer with _bool_ from my point of view, but on the other hand there is really no need for the additional include.
Regards
=> Fix for issue #554

cue.c
buf is created by mmap and destroyed by munmap. there's no need to free it.
see https://github.com/cmus/cmus/issues/559
=> fix a crash where buf is freed but never alloced

ip/flac.c
The flac library does not output decoded data until it has processed a
certain amount of input data or until the end of the stream is reached.
The old version of the code did not take this into account. In
particular, us having inputted all of our data into the flac plugin does
not mean that the flac plugin has outputted all of its data yet.
Hence we remove the `priv->pos == priv-len` check and instead ask the
flac library directly if it's done.
---
Fixes #440.
=> Fix flac plugin for small files

op/pulse.c
The pulse plugin might be much better than the alsa plugin but it doesn't matter if it simply gives the user a blank screen. With this change the alsa plugin is the new default on an alsa/pulse machine.
=> Reduce pulse plugin priority

Doc/cmus.txt, format_print.c, options.c, options.h
With this change users can now use the option `time_show_leading_zero=true` to always show two digits for the minutes (this is the default):
And `time_show_leading_zero=false` to only show 2 digits padded with a space if the duration is more than 10 minutes:
=> added option to show or hide leading zero in minutes

configure, scripts/checks.sh
Hi,
Here are two small OpenBSD patches for cmus (I maintain the official OpenBSD port, and I wrote the sndio output plugin a few years ago).
The first patch removes the -pthread special case for OpenBSD. No supported OpenBSD release requires this anymore.
The second one checks for sndio everywhere, since it's no longer BSD-only (and the current code omits Bitrig, an OpenBSD fork):
http://www.sndio.org/
I think these 2 patches + 84f33584be9150d9783751dc3ccbd726e33072c7 ("Support 32-bit/24-bit encoding in sndio output plugin") could be backported to 2.7.2, FWIW.
=> Small OpenBSD/sndio fixes

ip/ffmpeg.c
This clean-up will support ffmpeg avcodec api version >= 54. 
for the same reason in https://github.com/cmus/cmus/commit/62dcfb35b29b808d4b8cd9cf27ae3ab20db8ef0c and https://github.com/cmus/cmus/pull/539
we're not going to support super old library versions. 
ffmpeg bumped their avcodec api version to 54 in version 0.11 which released in mid 2012. See https://github.com/FFmpeg/FFmpeg/blob/release/0.11/doc/APIchanges
some more reference: 
The following are the ffmpeg api version bump dates:
2013-03-xx version 55
2014-08-09 version 56
2015-08-28 version 57
See https://github.com/FFmpeg/FFmpeg/commit/e88103a7f92cf27a2868b50acc8a9912f6088249
https://github.com/FFmpeg/FFmpeg/commit/1985c2e75c607ac51bfd8dc87d2957a5edf2b6f8
=> remove dead code for ancient ffmpeg versions.

command_mode.c, utils.h
=> remove trailing spaces from key in cmd_unbind() and cmd_showbind()

op/sndio.c
When par.bps is unset sndio will default to SIO_BPS(bits) ("the
smallest value for bps that is a power of two and that is large enough
to hold bits" sio_open(3)).  4 bps in the case of 24 bits which leads
to a horrible whitenoise screeching sound.
I'm unsure why it worked in cmus 2.7.1 without this change.
=> Use 3 bytes per sample when playing 24-bit files in op/sndio

Doc/cmus.txt, command_mode.c, data/rc, keys.c
Implements #515.
Lets you bind the search commands, which are hard coded to `/` and `?` up to now.
The search mode in the command line is still indicated by `/`/`?`. This could be changed to e.g. `search: `/`backward search: `. Thoughts?
=> made (backward) search a bindable command

ui_curses.c
unless the ESCDELAY environment variable is set.
fixes #618
=> set curses escdelay

Doc/cmus.txt, options.c, options.h, ui_curses.c
Allow overriding of the starting view when cmus opens. Default is still TREE_VIEW.
=> Added option to select starting view

op/oss.c
Adding support for AFMT_{S24,U24}_{LE,BE} will make the format
selection even more difficult to read, so while here replace it with a
simple lookup table.
Tested on FreeBSD.  The symptoms of using the wrong format were
the same as with the sndio plugin (#613).
=> Use correct format for playing 24-bit files with op/oss

expr.c
I just discovered the `expr` struct isn't being fully initialized.
=> Fix initialization of union

Doc/cmus.txt, options.c, ui_curses.c
Hi there! This is an initial attempt at adding an album duration format option as mentioned in issue #449. I am sure this will require more work, but I wanted to get feedback on it before I go any farther. This is what it looks like:
Please let me know what I need to do to get this into a state where it can be merged. Thank you!
=> initial attempt at album duration

Doc/cmus-tutorial.txt, Doc/cmus.txt
The [f]ollow options was not on the tutorial and on the documentation.
=> Add the 'follow' option to tutorial and documentation

tree.c
Otherwise a track might be added to the library but not to the tree.
Fixes #417
=> Change album_add_track to always add the track

command_mode.c, search_mode.c
Resolves #482. `C-p/C-n` in command mode and search mode now act like the Up/Down arrow keys, respectively.
=> Added C-n/C-p for history navigation

command_mode.c
Commands like `:player-play ~/Music/filename.mp3` now work as expected.
=> Enable tilde expansion for :player-play

mpris.c
Rename MPRIS property `CanGoPrev` to `CanGoPrevious` in accordance with the [spec](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:CanGoPrevious).
=> Fix MPRIS CanGoPrevious property typo

Makefile, scripts/checks.sh
a4540236 broke lazy expansion of -dep-$@ in CFLAGS by performing an :=
assignment of CFLAGS in the Makefile.
=> Fix depfile generation

track_info.c
Just a really teeny fix: `track_info.c` accidentally included `stdatomic.h` twice, and now it doesn't.
=> Remove double-inclusion of stdatomic header

Doc/cmus.txt, data/rc
By default vim binds `^U` and `^D` to half-page up/down, so cmus should as well.
=> Make ^U/^D default for half-page up/down motions

cue.c, cue.h, ip/cue.c
XLD ( http://tmkk.undo.jp/xld/index_e.html ) creates compilation cue as following.
This pr supports such compilation.
```
REM COMPILATION TRUE
```
=> handle "REM COMPILATION TRUE" in cue generated by XLD

Makefile, delegate.c, delegate.h, options.c, player.c, player.h, ui_curses.c
Tl;dr: The UI thread no longer waits for the player to perform its requests (player_next, etc.) Instead it simply schedules the commands and returns immediately. This allows the UI thread to reply to `cmus_get_next` requests that occur while the player holds its locks.
Fixes #574.
=> Fix #574 (deadlocks in player.c)

Doc/cmus.txt, cmus.c, cmus.h, command_mode.c, mpris.c
I've implemented what I described before in https://github.com/cmus/cmus/issues/756.
It detects X11 system, loads `libX11` using `dlopen` and raises the terminal window.
It also adds `raise-vte` command and implements `Raise` method in MPRIS protocol.
=> Add command to raise VTE window + implement MPRIS Raise method

cue.c
Cue files which have a byte order mark are improperly parsed. Currently, if there is a byte order mark present and a valid cue token on the first line of the file, the token is not recognized and the first line of cue data is missed. For my use case, the first line would the the album title, and therefore any cue files in my library would be displayed with `<No Title>` as the album title.
This commit looks for the presence of a UTF-8 byte order mark and advances the file buffer beyond it. In UTF-8, the byte order mark isn't recommended and really serves no purpose other than to signify the beginning of a UTF-8 stream.
=> Correct parsing for cue files with byte order mark

ip/ffmpeg.c
I don't know that much about ffmpeg development, but it seems as if the cmus plugins uses some deprecated constants/symbols that result in build errors with newer ffmpegs (especially fairly recent source builds). This fixes building with newer ffmpeg builds, and also fixes https://github.com/cmus/cmus/issues/782, for example. I don't know yet if cmus wants to support the latest ffmpeg and possibly drop support for older ones, but maybe take this PR into consideration at a new point release.
=> Fix ffmpeg plugin build

player.c
Skip track when doing a relative seek past track length. Jump to five
seconds before track end when doing an absolute seek.
Tested working with mad, modplug and ffmpeg input plugins.
Closes #802
=> Skip track when seeking past track duration

comment.c
I tag my FLAC collection with Meta on macOS:
https://www.nightbirdsevolve.com/meta/
…but compilations don't appear as they should with cmus, because Meta only adds a `PARTOFACOMPILATION=1` tag and no `COMPILATION=1` tag. cmus doesn't know the former.
Upstream tells me that they're just following what iTunes is doing (but they'll add support for a `COMPILATION=1` tag in a future release), but in the meantime the following PR lets us accept `PARTOFACOMPILATION` tags as well.
Googling a bit reveals that some other programs might write this tag as well, although `COMPILATION=1` is probably more common. But since it looks like there's no real standard for this, I don't see many drawbacks of accepting this variant.
=> Accept PARTOFACOMPILATION tag

misc.c
While doing some testing, I typed "export CMUS_PLAYLIST_DIR=; ./cmus". Not only did that break cmus, it produced a very unhelpful error message. Better to use get_non_empty_env.
=> Change to get_non_empty_env for CMUS_PLAYLIST_DIR.

ui_curses.c
On ultra wide screens cmus crashes. It seems to be due to buffer overflow when printing `print_buffer`. I bumped up the size of the buffer and it fixed the issue, at least on my screen. You can reproduce the issue on a regular screen by reducing the font size.
A more thorough solution would probably be to use bounds checks whenever printing the buffer. I tried that solution but it quickly got messy. My first attempts fixed the crashes but messed up the formatting of the output. A dynamic buffer might be easier to switch to but has that approach also has its own issues.
=> Increasing print buffer to fix crashes on ultra wide screens

contrib/cmus-updategaim.py, contrib/cmus-updatepidgin.py
Changed shebang to use /usr/bin/env to get the python interpreter
updatepidgin: We simple remove the useless print without parenthesis.
=> Make contrib/cmus-update*.py scripts use env python and fix pidgin with py3

format_print.c, input.c, output.c, utils.h
clean compile with gcc 8.2.0 and clang 7.0.1 (except for ffmpeg deprecations)
=> Fixes various compiler warning

Makefile
Without this, `convert.lo` doesn't get removed when running make clean.
=> Add *.lo to clean in Makefile

ip/ffmpeg.c
- av_register_all is no longer needed since 4.0
- AVStream::codec is deprecated since 3.1
- avcodec_decode_audio4 is deprecated since 3.1
=> Fixes ffmpeg deprecations

Doc/cmus.txt
bind -f must be used to override existing keybindings.
=> Add note about overriding keybindings using rc (closes #742)

ip/flac.c
flac inflates the bit rate to 32bit for 24bit files, but declares 24bit in
the sf structure.
fixes #644
=> Fixes incorect bit rate declaration for 24bit flac

mpris.c, uchar.c, uchar.h
Partly addresses 847. All bytes that are invalid utf8 are converted
to <xx>, just like other areas in cmus. This is a temporary fix.
=> Ensures all data sent on dbus is in utf8 (#847)

command_mode.c
this is the original behaviour prior to fead80b
fixes #887
=> Makes :quit only prompt if -i is given

misc.c, misc.h
The variable wasn't used anywhere in cmus. Having it made cmus
unnecessarily required env var USER or USERNAME to work.
=> misc_init: remove variable user_name

editable.c
Marking all tracks in library/playlist/queue view and moving them using p/P would crash cmus. Fix this by updating window state *before* setting selected track after the move.
This fixes #599; note that moving all tracks is a no-op, but it’s still better not to crash.
=> Fix a crash when moving all tracks in a view

Doc/cmus.txt, command_mode.c
Implements #930
Allows the push command to be used with no arguments. This results in an empty command line.
=> Allow push to accept no arguments

format_print.c, id3.c, uchar.c, uchar.h, ui_curses.c
The narrowing cast happens with the second argument in the call to
`u_set_char()` in `format_parse()` in format_print.c. The argument is
`str->len`.
Before this commit, `&str->len` was cast to `(int *)`, despite `str` being
a `struct gbuf` whose `len` member has type `size_t`.
This does not cause an issue on 64-bit little-endian systems because a
cast to `int *`, though narrowing, points to the bottom four bytes of
`str->len`, and so the incrementing of the local copy of the `idx`
parameter in `u_set_char()` and then the assignment back to `*idx` doesn't
have any undesired behavior.
64-bit little-endian
```
|0|1|2|3|4|5|6|7| (str->len, numbers indicate byte significance)
^
|
|_(size_t *)
|0|1|2|3|
^
|_(int *)
```
An increment here on 64-bit little-endian increases the value held in
byte …
=> Fix segfault on ppc64 caused by narrowing cast

expr.c
There is a small typo in expr.c.
Should read `special` rather than `speacial`.
=> docs: fix simple typo, speacial -> special

mpris.c
The `title` and `album` mpris2 fields were sent as list of strings,
which caused issues with the GNOME integrated notification system.
The mpris2 specification states that these two fields should be strings,
not lists of strings.
=> Fix type of MPRIS2 fields title and album

keys.c, pl.c, pl.h
Previously, scrolling or clicking within an inactive playlist pane would not select it; the event would just act upon the currently selected pane. This behavior was not consistent with the library view.
fixes #1010
=> Make mouse behavior on playlist window consistent with library

Doc/cmus-remote.txt
This fixes #979.
While experimenting with this, I noticed that my zshell's autocomplete doesn't mention -f either, nor does it mention other important options like even -Q. I imagine that it has to do with this file:
https://github.com/eshrh/cmus/blob/remote-f-doc/contrib/_cmus
I'll look into this further, and maybe open another issue.
=> Add -f, --file options to cmus-remote manual

cue.c, cue.h, ip/cue.c
Tools like Exact Audio Copy use the "REM DISCNUMBER" comment as a convention to store the disc-number of a multi-disc album within the cue-sheet.
Other players that implement this convention are for example Foobar2000 or Clementine.
Currently in cmus track sorting wrong for such albums, alternating tracks with the same numbers from disc 1 and disc 2 etc.
=> Add support for 'DISCNUMBER' REM-field in CUE-sheets

comment.c, comment.h, track_info.c
These tags target -23 LUFS while REPLAYGAIN targets -18 LUFS, thus we
need to add a bias of 5 to get a loudness that's consistent with
REPLAYGAIN'd tracks.
Closes #785
=> Support R128_TRACK_GAIN / R128_ALBUM_GAIN tags

mpris.c, uchar.c, uchar.h
fix #885 
description of bug:
https://github.com/cmus/cmus/issues/885#issuecomment-477761446
to correctly calculate the space required for u_to_utf8, account for control characters and invalid utf8 being printed as `<XX>` by u_set_char.
I called my new functions "print size" because u_set_char and u_to_utf8 are under a comment that says "Printing functions, these lose information"
=> properly calculate size of print string from u_to_utf8

cue.c
I noticed, that cmus doesn't play pregaps of tracks from cue sheets.
Here's a short explanation of this change:
The cuesheet defines this:
```
Index  1         0        1
| Track 1 |     Track 2      |
|         | Pregap |         |
before | Track 1 | *skip* | Track 2 |
after  | Track 1          | Track 2 |
```
Cmus calculated the lenth of track 1 by substracting index 0 from track 2 with index 1 from track 1.  However the start of track 2 is always index 1 of track 2.  So by adding the pregap to the lenght of track 1 we make sure that the user hears the transition before track 2 starts.
Here's a short example which is the transition from track 2 to track 3 on Beastie Boys' "Hello Nasty":
[pregap.tar.gz](https://github.com/cmus/cmus/files/5500491/pregap.tar.gz)
It contains 10 seconds of …
=> cue: play pregaps of songs by adding them at the end of the previous song

Doc/cmus.txt, cmus.c, options.c, options.h
closes #696 
Adds a new option to prevent playback continuing onto the whole library
once the end of the queue is reached. Defaults to false. Enable with
`:set stop_after_queue=false`
=> Stop after queue (resolves #696)

Doc/cmus.txt, options.c, options.h, ui_curses.c, ui_curses.h
=> Add tree width options

pl.c
fixes #893 
When starting playback of a playlist and shuffle is on, the first track
in the playlist was started rather than the first in the shuffled list.
This would result in playback stopping before reaching all files in the
list.
=> Shuffle first track (#893)

ui_curses.c
Fixes gcc warnings about format trunctations
=> Fixes truncation warnings by replacing %s with %.s

pl.c
* Only select the playing track when selecting a playlist with shuffle enabled. This fixes the regression in #1008 which caused the currently playing track to be selected when activating any row in the playlist view.
* Remove (harmless) duplicate pl_select_playing_track call.
* Make the relationship between the follow option and the code which selects the shuffled track more explicit.
See https://github.com/cmus/cmus/pull/1008/commits/8fdd16a5013eb56922f531ad0608e78d4f073be3#r560385478. Fixes #1046.
=> Fix playlist track selection

ui_curses.c
Previously we allowed for 511 columns and would crash if the window was
larger than this. The browser tab had an even lower limit when the path
contained multibyte characters.
=> Limit max draw width to 1023 columns

ui_curses.c
The uninitialized variable, active, would sometimes cause cmus to segfault while accessing the pairs array based on its value.
This commit also fixes implementation-defined behaviour for the implicit cast of track->marked.
fixes #1093
=> Initialize active to zero in print_editable

ui_curses.c
Originally, there was the editable_active variable in ui_curses.c to
indicate whether the window is active. However, this variable was
removed in #1051, presumably by mistake. It also leads to the active
variable being uninitialized in print_editable, causing #1093.
The uninitialized variable issues was fixed in #1094, but unfortunately
in a wrong way: it simply assumes all windows are inactive, leading to
incorrect colors in many views.
This commit restores the old logic of editable_active (renamed to
win_active for consistency). Now the colors should be correct.
=> Handle colors in active windows correctly

ui_curses.c
Previously, window size variables (tree_win_w, track_win_w, and win_w)
are only initialized in main_loop, which can lead to negative string
lengths if they are used before initialization, causing segfault.
Fixes #1117.
=> Initialize window size in init_curses

Doc/cmus.txt, mixer.h, op.h, op/coreaudio.c, op/mixer_alsa.c, op/pulse.c, options.c, options.h, output.c, output.h, ui_curses.c
This also bumps the output plugin ABI to add support for returning multiple mixer FD lists, but preserves compatibility with older plugins.
closes #1139 
**Note:** @flyingmutant, when you merge this, please do a merge rather than a squash to keep the plugin changes separate.
=> Implement pause_on_output_change option

job.c, load_dir.h
When adding directories, ignore folders that contains a .nomedia file.
This mimics the convention of the Android OS[1] to tell smartphone apps
not to display or include the contents of the folder, which is also
supported by different Desktop programs[2] and other multimedia
platforms[3]
[1] https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory#Android
[2]
* https://forum.strawberrymusicplayer.org/topic/412/exclude-paths-directories-files-from-library/2?_=1652534386411&lang=en-US
* https://github.com/clementine-player/Clementine/pull/5327
[3] https://kodi.wiki/view/Update_Music_Library#Exclude_Folder
=> Add support for .nomedia file

comment.c, ip/opus.c, player.c, track_info.c, track_info.h
This pull request incorporates the output gain value from opus files when deciding if the replaygain adjustment would go over the 1.0 peak limit. (Issue #1200)
I don't know if this is a good solution to this problem and would appreciate any feedback.
=> Take opus output gain into account when checking replaygain_limit peak

comment.c
These values are experimental. I've no explanation for why "TSO2" is
used rather than something like "album-artist-sort".
This is particularly relevant for mp4/m4a as the mp4 input plugin is
currently broken/disabled on many platforms.
Fixes #1164.
=> Recognize artist/album sort keys from ffmpeg plugin

ui_curses.c
Also avoid bogus titleline draws before curses initialization.
Fixes #1204, #1256.
=> Draw title and command lines on first update

ip/mp4.c
This isn't uncommon actually; for quite a lot of the tracks in my library the first "MP4" tag is tag 2.
=> ip/mp4: Use MP4FindTrackId() rather than assuming it's "1"

ip/ffmpeg.c
=> Remove AV_CODEC_{CAP,FLAG}_TRUNCATED for FFmpeg 6 compatibility

configure, mpris.c
Should help FreeBSD users have media key support. Closes #1133.
=> Introduce basu as an option for MPRIS control

track_info.c
Although this might be up for debate, but to me it seems like this was probably always the intended behavior.
Fixes #1262.
=> Search should only try filename when there are no tags

scripts/checks.sh
In recent clang version the -Wint-conversion warning became an error. So the function detection doesn't work anymore.
Compiling this code with clang
`char resizeterm(); int main(int argc, char *argv[]) { return resizeterm; }`
results in error:
`main.c:1:62: error: incompatible pointer to integer conversion returning 'char ()' from a function with result type 'int' [-Wint-conversion]`
=>  Fixed function detection. check_function failed to compile due to clang -Wint-conversion warning became error.

Doc/cmus.txt, command_mode.c, data/rc
Added to the default mouse scroll binds, which is quite intuitive and seems to be how web browsers like to handle it. (For reference they do allow cycling when activated by keyboard shortcut, although we don't have any default keyboard binds for left-view / right-view.)
Closes #1241.
=> Flag to prevent cycling with left-view / right-view

Doc/cmus.txt, options.c, options.h, ui_curses.c
This uses bracketed paste, where supported (xterm, win10, iterm2, etc), to prevent pasted text from being interpreted as commands unless the new `block_key_paste` option is disabled.
closes #1270
=> Implement option to ignore pasted text in normal mode

Doc/cmus.txt, options.c, options.h, tree.c
By default they are still sorted by date, which is the current behavior.
I considered to also add an equivalent of smart_artist_sort, to strip "The" from album names when sorting. It could be nice to add for consistency, but I find it's not that useful when the list of albums under a given artist tends to be quite small anyway.
Closes #909.
=> Add option to sort albums by name in tree view

Doc/cmus.txt, comment.c, track_info.c, track_info.h, ui_curses.c
Allows displaying the number of discs of an album. Can also be used as a condition. Shorthand is `%T`.
I added it because I wanted to display the disc number only if the total number of discs is greater than one.
=> Add %{totaldiscs} to available format string

track_info.c
The Q7.8 encoding is only capable of accurately storing 2 decimal places. It's misleading (and ugly) to present it as otherwise when printed.
=> Reduce R128 gain precision to 2 places of decimal

format_print.c
Print for example "5.0" instead of "5." with an awkward trailing decimal point.
This formatter is only used for printing replay gain info (rg_track_gain etc.) which by default we don't.
=> Fix formatting of whole number doubles

cue.c, cue.h, ip/cue.c
The cue plugin will fail when parsing multiple FILE entry because of the postion check and fixed file entry.
Make the parser more robust so it can paser the cue sheet with multiple files like this
```
PERFORMER "XXX"
TITLE "XXXXX"
FILE "XXXX1.wav" WAVE
TRACK 01 AUDIO
TITLE "XXX"
PERFORMER "XXX"
INDEX 01 0:00:00
TRACK 02 AUDIO
TITLE "XXX"
PERFORMER "XXX"
INDEX 01 4:34:44
FILE "XXXX2.wav" WAVE
TRACK 03 AUDIO
TITLE "XXX"
PERFORMER "XXX"
INDEX 01 0:00:00
```
=> Allow cue plugin to parse cue sheet with multiple files.

Doc/cmus.txt, command_mode.c, pl.c, pl.h
This PR implements the commands "pl-delete" and "pl-delete-all" that remove playlists for use with cmus-remote.
Other playlist management functionality needs further design discussion but these commands should be sufficient if all playlists are managed externally (which is my use case).
Partially addresses #1066
=> Add commands for external playlist management

gbuf.c
Such characters are stored as one byte but print as "<07>" for example.
(Although I'd argue we should just print them as '?' and save all the extra trouble.)
=> Fix gbuf to account for print width of control characters

lib.c
Really just checking for duplicates again when unfiltering. A bit messy but it does the job.
The "entryp" naming is consistent with `hash_remove()` etc.
Relates to #423.
=> Fix ignore_duplicates missing filtered tracks

ip/nomad.c
(Which as I understand it is just a wrapper for LAME.)
This is needed for gapless playback on these files.
=> Parse LAME header when mp3 was created with libavcodec

configure, scripts/utils.sh
On Apple Silicon, Homebrew doesn't install ARM packages to the global header/library paths. This means that the common package dependencies `faad2` and `mp4v2` can no longer be detected by checking `/usr/local`, so `configure` fails to find them and disables AAC and MP4.
This is fixed by using `pkg-config` to check for those dependencies, since Homebrew's `pkg-config` search path accounts for the CPU architecture, and gives the correct results on both Intel and ARM.
I left the previous behavior in place as a fallback, for systems that have the libs installed globally without a working `pkg-config`.
Minor housekeeping: I also changed the temp file cleanup at the end to use `-r` with `rm`, since on macOS the configure script generates `.dSYM` directories from its temp file builds, and the …
=> Fix library detection on Apple Silicon

ip/ffmpeg.c
The LIBAVCODEC_VERSION was bumped to 59.24 for this API.
Fixes #1329.
=> [FFmpeg] Fix version check for new channel layout api

configure, scripts/checks.sh
Simply try taking the address of the function instead of doing funny stuff with the pointer.
=> Fix configure function checks for recent clang versions

player.c
If continue_album=0 and the current or next track doesn't have album metadata, a strcmp with a null pointer will be done at the end of the track. Ensure track_info.album is non-null like other parts of cmus.
The continue_album option was added in f3ed07ee3d46b2bc98f98247654729b02457409b.
=> Fix possible null dereference when continue_album=0

comment.c, ui_curses.c
It seems like that's probably the main intended use, for instance in id3v2 the disc number would be recorded in TPOS (Part Of Set). The name "part" is simply more generic as not everything is stored on discs.
As a real world reference, EasyTAG uses PART (and ignores DISCNUMBER) when reading/writing the "CD" field as an APE tag.
Fixes #1313.
=> Make PART / PARTNUMBER aliases for DISCNUMBER

configure
This makes it match the other libraries, and it's clearly a mistake since the line below appends NCURSES_CFLAGS.
=> Fix missing NCURSES_CFLAGS in configure try_compile_link

ip/mad.c
In input.c, ip_close calls ip->ops->close, then closes ip->data.fd (aka ip_data->fd) if fd is not -1. In ip/mad.c, close_func closes ip_data->fd without setting it to -1.
May be the cause of the fdsan failure reported in termux/termux-packages#18954. I've been looking at all the close calls and tracing the callers, and this seems to be the most likely issue.
=> Fix potential double-close in ip/mad

Doc/cmus.txt, ui_curses.c
I noticed if I have a `view` command in my rc config (e.g. `view playlist`), cmus segfaults at startup. I can provide a more detailed backtrace if needed, but I thought it's clear enough what's happening from the description in the commit message in here.
I also added a note in the manpage to say not to use `view` in the rc; I assume you're not supposed to do that, because the `start_view` option exists instead. I feel like `view` used to either work or do nothing, for old versions from years ago, because I had this in my rc for an old install. Using `view` in the config could also throw an error, I wasn't sure what's preferred.
=> Fix view segv in rc config

ip/aac.c, ip/mp4.c, utils.h
At least for me there can sometimes still be soft clicks between tracks that aren't there when playing back the externally decoded wavs, but the buffer looks okay and gapless mp3 has the same clicks so I guess it's an unrelated hitch in the player or on the output side. In any case this is a very mild artifact compared to what we had before.
Closes #1280.
=> Trim gaps from mp4 playback

job.c, lib.c, options.c, pl.c, pl.h, play_queue.c
Slightly overengineered as it could be done without a loaded event, but I wanted to avoid surprising behavior in the unlikely case where the playlist is cleared offline and then repopulated some time after cmus was started.
Fixes #729.
=> Remember playlist position when resume=true

.github/workflows/build.yml, Doc/cmus.txt, Makefile, configure, op/aaudio.c
Support native audio on Android 8.1 and later.
- Better battery life.
- Configurable latency.
- Configurable capture policy.
- Configurable sharing mode.
- Configurable spatialization.
- Full multi-channel audio support.
- Supports `pause_on_output_change`.
---
To test this in Termux, compile and run cmus on the device. You can also compile just the plugin with `$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target aarch64-linux-android26 -shared -o aaudio.so -fPIC -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -Werror=unguarded-availability -Wall -std=gnu11 op/aaudio.c -laaudio`, and copy it to `~/../usr/lib/cmus/op`.
Set the output plugin with `:set output_plugin=aaudio`.
This plugin has a higher priority than pulse, but will fallback on unsupported devices.
=> Implement AAudio output plugin

configure, scripts/configure.sh, scripts/utils.sh
Many packages need a workaround for setting the prefix without this.
fixes #1261
=> Improve compatibility with autoconf-style configure options

options.c
I missed updating the values list when adding `color_statusline_progress_attr`. This was causing the "bold" to match with `color_win_title_attr` instead of `color_trackwin_album_attr`.
=> Fix a couple of wrong *_attr defaults

Doc/cmus.txt, command_mode.c
The `load -p whatever.pl` command does not work, and results in the error `:load only works in views 1-2`.
The `load whatever.pl` command only works in views 1-2.
The `load -l whatever.pl` works in all views.
The initial implementation of the load command was done in 8d3cbc51fb13d91468c768dfc683f8101f670825, and was consistent with the documentation added in eec4e5e819c7af1586d544d841f1fac273796ee0.
Support for loading into the playlist view was intentionally dropped in 5563e0c94bfca08c08628007abc477e47437fec3, but the documentation and arg parsing was not updated.
fixes #1304
=> Fix load command args

op/coreaudio.c
=> op/coreaudio: Stop using deprecated kAudioObjectPropertyElementMaster

play_queue.c, play_queue.h, ui_curses.c
The format option "total" will display the total time in the library or the current playing list, but if the queue is active it should instead display the total time of the queue.
=> add play_queue total_time

Makefile
The LDFLAGS variable substitution was left behind after 85237ec35370f0837c8be3cd1503f9164dbf6703.
=> Fully remove libcue

pl.c
The manpage says filter expressions can be used in views 2-4, and I don't see the utility in `:mark` inverting the selection in the playlist view.
=> Fix :mark on playlist view so filter is used

Doc/cmus.txt, op/aaudio.c
This fixes buffer underruns on the Pixel 9 due to the default selected buffer size being faster than cmus can produce audio.
There's probably a better way to deal with this, but it works.
=> Set the minimum requested AAudio buffer capacity

configure
It's required for av_strerror.
=> Check for libavutil pkg-config

.github/workflows/build.yml
The updated list (including order) is copied directly from the README. No additions. Removals:
- bash-completion (not used)
- libcue-dev (not used)
- libroar-dev (no longer available, breaking the CI build)
=> [CI] Update dependency list to fix ubuntu build setup

player.c
Bad values for output_plugin set in ~/.config/cmus/rc or ~/.config/cmus/autosave prevent output_plugin from being initialized.
This fixes that.
=> Try to fallback to any plugin upon failure to init output plugin

input.c, ip.h, ip/ffmpeg.c, track_info.c
If a stream specifies its bitrate in an "icy-br" header, we can use it to populate the bitrate in the track info. Without this fix, no bitrate was displayed for a stream, either in the track info or the status bar.
Also changed a print format specifier from %ld to %lld to fix a warning as the former is too small for the int64_t type.
=> Fix for missing Icecast streaming bitrate display.

Makefile, op/alsa.c, op/mixer_alsa.c
I'm spamming at this point, but this is pretty useful :)
Alsamixer and i3status and aplay (with -M flag) display so-called 'mapped volume' by default (see `man alsamixer` "VOLUME MAPPING"), so I added it to alsa mixer plugin. `mixer.alsa.mapped_volume` config option turns it on. It's enabled by default because Alsamixer and i3status do it, I think its ok.
=> op/mixer_alsa: alsamixer's volume scale; setting mixer control like aplay does it
