cue.c, cue_utils.c, cue_utils.h, mp4.c, utils.h
Turns cue garbage disposal into two more general functions
=> Fix mp4 garbage output

ffmpeg.c
Certain formats (such as ogg/opus) contain metadata in more than one
part of the file. ffmpeg does not automatically merge this metadata so
we have to manually collect it from all streams.
Closes #313
=> Fix missing ffmpeg metadata

Doc/cmus.txt, ao.c
=> Enable user to set device interface when using libao plugin.

coreaudio.c
Put a few things from _open to _init, _close to _exit. Add channel support. Make syncing sample rate feature more precise by detecting device capability first.
=> A few fixes/enhancement to the CoreAudio plugin

ffmpeg.c
We have received the included patch in Debian. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810557 for details.
=> Replace deprecated FFmpeg API

Doc/cmus.txt
I just noticed that this needs an update.
=> referring to github for issues/feature requests in man page

configure
=> add missing CFLAG

ffmpeg.c
I've also removed the guard and ordered everything by name to make it a bit more tidy.
=> add mkv support

ffmpeg.c
=> Fix ffmpeg segfault

data/gruvbox-alt.theme
Here is an alternate take on the gruvbox palette. Despite being based on the same colors it looks distinctly different.
=> add gruvbox-alt.theme

Doc/cmus.txt, input.c
Reverts cmus/cmus#442
https://github.com/cmus/cmus/pull/442#issuecomment-230155455
=> Revert "make IP priority an option"

Doc/cmus.txt
=> Escape asterisk in man page.

flac.c
There's currently a bug in player. Seeking 24bit doesn't work for now.
@flyingmutant  any idea why?
=> support 24bit playback for flac

.travis.yml, configure, track_info.c, track_info.h, ui_curses.c, ui_curses.h, worker.c, worker.h
Addresses the issues raised in #507 and some more.
Coincidentally 3a8091b might (or might not) fix #505.
=> Release fixes

op/coreaudio.c
which will make volume querying a little bit faster
=> cache device_stereo_channels information, and add mixer_fds to coreaudio

locking.c
This makes the code both simpler and faster.
=> Improve fifo_mutex performance

pl.c
Unless another playlist is already playing.
Closes #545
=> Make player-play play the visible playlist

.travis.yml, Makefile, browser.c, configure, cue.c, cue.h, cue_utils.c, cue_utils.h, file.c, file.h, ip/cue.c, job.c
=> Remove libcue dependency

locking.h
=> Remove compound literal from constant expression

command_mode.c, pl.c, pl.h
=> Fix some playlist bugs

Doc/cmus-tutorial.txt
Also made a small change to sentence syntax
=> Add next/prev playback controls to list in step 3

configure, ip/wavpack.c
=> require wavpack >= 4.40 and remove obsolete preprocessor check

format_print.c
=> Fix segfault in format_skip_cond_expr

README.md
The old link moved to a new location.
=> Fixed Linux kernel style link

player.c
=> fix for issue #711

ui_curses.c
=> Adding albumartist to status_display_program.

data/dracula.theme
Needs a dracula (or at least dark) terminal theme.
=> Added dracula theme

Doc/cmus.txt
=> Fix #27 - Add documentation for passwd option

misc.c
Add logic to configure the playlists directory from an environment
variable CMUS_PLAYLIST_DIR, similar to CMUS_LIB_DIR & CMUS_DATA_DIR.
=> Add support for CMUS_PLAYLIST_DIR.

.travis.yml
Also, add OSX build (though that can be removed if you prefer.)
=> Fix build error on CI

command_mode.c
=> Makes save -p consistent with documentation

ui_curses.c
When leaving the main loop, the player status is set to "exiting" and
the status program is spawned just with the arguments "status exiting".
Partially implements #640.
=> added "exiting" player status

Makefile, configure
Support for elogind, as already reported here: https://github.com/cmus/cmus/issues/844
=> Add support for elogind

browser.c, command_mode.c, filters.c, help.c, input.c, pl.c, ui_curses.c, ui_curses.h
=> Fixes hanging when terminal is closed while promting

ip/mp4.c
=> ip/mp4: add metadata support for bpm/tempo

Doc/cmus.txt, options.c, player.c, player.h
When false, stop playing at the end of the album.
=> Add `continue_album` option

contrib/_cmus
=> Update zsh completion

data/gruvbox-warm.theme
A warmer version of gruvbox.theme.
=> Add gruvbox-warm.theme

Doc/cmus.txt, cmus.h, command_mode.c, editable.c, editable.h, lib.h, pl.c, pl.h, tree.c
=> Add -n option to win-add-{l,p,Q,q} to prevent selecting the next item

Doc/cmus-remote.txt
I just ran into this problem and having this here could potentially help individuals in the future if [this Sourceforge e-mail thread](https://sourceforge.net/p/cmus/mailman/cmus-devel/thread/20070109205250.0c06dddd.dnk000@gmail.com/) ever goes away.
=> Adding "--server SOCKET --passwd PASSWORD" section

Doc/cmus.txt, data/rc, keys.c
=> Implement mouse events for status bar

Doc/cmus.txt, data/rc, keys.c
=> Implement mouse events for title bar

Doc/cmus.txt, data/rc
From https://github.com/cmus/cmus/pull/1024#discussion_r555295156.
These improvements are for the documentation only and do not affect the functionality of the keybindings.
=> Documentation improvements for keybindings and some commands

ui_curses.c
#1025 increased the length of the largest keybinding name.
=> Increase help view keybinding width

data/amazon.theme
=> add amazon.theme

Doc/cmus.txt, format_print.c, format_print.h, options.c, options.h, uchar.c, uchar.h, ui_curses.c
=> Indicate elided text with "…" & related formatting tweaks

Doc/cmus.txt, cmus.c, cmus.h, command_mode.c, command_mode.h, data/rc, lib.c, lib.h, options.c, options.h, pl.c, player.c, track.c, track.h, tree.c, ui_curses.c
...for the library. Playlists aren't flexible enough. If we wanted playlists to support album shuffle, we'd probably need to consider reimplementing them as secondary libraries.
Closes #641.
=> Add album shuffle mode

ip/ffmpeg.c
Fixes #812
Fixes #895
Fixes #1063
Fixes #1081
Credits: @gdrbyKo1
=> ip/ffmpeg.c: fix ffmpeg API usage

ip/flac.c
=> Fixes channel map for multichannel flac files

mpris.c
=> Fix a typo in an error message

uchar.c
~~Range is selected based on https://en.m.wikipedia.org/wiki/Emoji#Unicode_blocks~~
~~This improves the experience somewhat but it's not really a fix. For that we probably need a library or drop in code.~~
=> Fix missing combining marks on last character in a field

.github/workflows/build.yml
macos-10 is no longer available.
=> Switch to -latest os in build workflow

Doc/cmus.txt, options.c, options.h, pl.c, pl.h, ui_curses.c
(Terminology is a bit difficult here, it's not really a tree and "playlist list" doesn't quite roll off the tongue...)
Requested in #897, etc.
=> Add auto_hide_playlists_panel option

contrib/_cmus
=> Fixed zsh autocompletion for --query/-Q

Doc/cmus.txt, lib.c, lib.h, options.c, options.h, tree.c
=> Ignore duplicates when adding tracks to the library

Doc/cmus.txt, Makefile, cache.c, cmus.c, job.c, options.c, options.h, pl_env.c, pl_env.h, player.c, ui_curses.c
See `pl_env.h` for more details.
closes #834
closes #245
=> Implement pl_env_vars option for library/playlist/cache relocation

op/pulse.c
=> pulse: don't drain the stream

Doc/cmus.txt, configure, options.c
=> Support italic text

Doc/cmus.txt, data/rc, keys.c
=> Add mouse bindings for right third of status bar

mpris.c, track_info.c
We only need to check if title is null to replace it with the filename in the track info.
=> Check only title in track title replacement

ip/ffmpeg.c
Old api is deprecated and sparks build warnings.
=> [FFmpeg] Switch to new channel layout api

command_mode.c
=> Fix unmute when using softvol

ip.h, op.h, output.c, sf.h
=> Support 384kHz sample rates

scripts/checks.sh
This brings the logic in line with the Makefile.
https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html
=> Include CPPFLAGS in configure checks

ui_curses.c
Otherwise it's almost impossible to edit things like `format_statusline` directly from cmus...
=> Show some context when editing middle of long cmdline

Makefile, configure
=> Fix ffmpeg configuration

Doc/cmus.txt
=> Fix documentation for passwd config option

ip/ffmpeg.c
\+ resample to a lower sample rate if needed, as some variants of DSD exceed the 524kHz we support internally -- and the 384kHz limit of at least some outputs (pulse).
Fixes #796.
=> [FFmpeg] Add .dsf to extension list (DSD support)

browser.c, filters.c, help.c, pl.c, search.c, search.h, track.c, track.h, tree.c
=> Fix tree restricted search infinite wrap

input.c
=> Rename 'Priority' to 'Default Priority' in --plugins

search.c
=> Prevent search from wrapping infinitely

Doc/cmus.txt, options.c, options.h, search_mode.c
https://github.com/cmus/cmus/issues/1332#issuecomment-2372443950
closes cmus/cmus#19
=> Implement option to start searches at the current position

options.c
New formats for the statusline, headings, and trackwin were introduced to streamline the interface and make better use of new features.
Update the config to the new defaults if we're upgrading from an old version of cmus (identified by the lack of the newly added format options in the autosave) after loading the autosave, but before loading the user's rc (yes, this does mean that if the user set a custom one via the command line rather than the rc, the user will have to reconfigure it).
See c454d4e4683143ed8fae9b4ba73ef215e8026e36, bad9b0c4291ad6a5e9f5de0e14a533ebd661ef41.
=> Apply new formats from #1317 on upgrade

window.c
(Or if we add/remove tracks to the current "window", although that's rather uncommon.)
=> Respect scroll_offset setting when resizing window
